<?php
/**
 * Created by PhpStorm.
 * User: direct
 * Date: 2018/3/2
 * Time: 16:44
 */

namespace app\blog\controller;
use cmf\controller\HomeBaseController;
use think\Session;

class Base extends HomeBaseController
{
    //    验证是否登录
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated st
        $this->isSign();
    }
    private function isSign(){
        //if(!Session::has('mobile')) $this->redirect('');
    }
}